tinted-theming/tinty

.github/workflows/release.yml

The `x86_64-unknown-linux-gnu` target requires GLIBC version >= 2.32, which cannot be run on old Linux distributions. Some rust utilities, e.g. [ripgrep](https://github.com/BurntSushi/ripgrep), [fd](https://github.com/sharkdp/fd),  will build `x86_64-unknown-linux-musl` target to get rid of the dependencies of GLIBC.

build: add musl targets

---

.github/workflows/release.yml
Cargo.lock
Cargo.toml
contrib/completion/tinty.bash
contrib/completion/tinty.fish
contrib/completion/tinty.ps1
contrib/completion/tinty.zsh
src/cli.rs
src/main.rs

This PR uses clap_complete to generate the completion script. To generate the completion script, use `tinty --generate SHELL > script_path`.
The reason why I added generated complete scripts to the Git index is that I want the schemes can be selected in completion directly. Currently, clap_complete cannot generate the complete results dynamically based on the outcome of another command, just like `tinty apply $(tinty list | fzf)` trick. Therefore, I have to manually change some places of the generated scripts.
However, I only make changes on bash only. The zsh, fish, and ps1 are untouched in this commit.
Here is the sample after `source tinty.bash` and hit Tab for completion:
Using [FZF Tab Completion](https://github.com/lincheney/fzf-tab-completion)

feat: add completion

---

README.md

The default config path should be `$XDG_CONFIG_HOME/tinted-theming/tinty/config.toml` instead of `$XDG_CONFIG_HOME/tinty/config.toml`.

docs: fix typo of default config dir

---

README.md

Just some typos I noticed while converting from Flavours. I also updated the swaywm example to be fully functional, similar to how alacritty example works, instead of nuking the entire config:
```toml
#~/.config/alacritty/alacritty.toml
import = ["~/.config/alacritty/colors.toml"]
#...
```
and
```ini
#~/.config/sway/config
include ~/.config/sway/config.d/*
#...
```

Updating README typos & More clear example

---

fixtures/schemes.txt
src/config.rs
src/operations/apply.rs
tests/cli_apply_subcommand_tests.rs

There still needs to be tests written and the documentation to be updated, but I wanted to get this out there to get some opinion on it first before committing to those.
First, the requirements for emacs that we are trying to meet:
- Theme file must end in `-theme.el`
- Theme file must be within the users `custom-theme-directory` (this one is easy)
- Theme file must be the same `theme name` as the theme provided within 
- Theme must be loaded by `theme name` via emacsclient
hurdle one was just properly identifying the emacs scheme files. The addition of an Optional parameter, `theme-file-extension` works around that: if this parameter is enabled it will search for the `scheme-name` with the `theme-file-extension` together. 
For example, `base16-nord` normally will look for any file that …

Feature: File-extension

---

CHANGELOG.md
Cargo.lock
Cargo.toml
Dockerfile
README.md
THIRD_PARTY_LICENSES.md
USAGE.md
about.toml
deny.toml
src/cli.rs
src/config.rs
src/constants.rs
src/main.rs
src/operations/apply.rs
src/operations/build.rs
src/operations/generate_scheme.rs
src/operations/info.rs
src/operations/list.rs
src/utils.rs
tests/cli_apply_subcommand_tests.rs
tests/cli_general_tests.rs
tests/cli_install_subcommand_tests.rs
tests/cli_list_subcommand_tests.rs
tests/cli_update_subcommand_tests.rs
tests/fixtures/schemes/tinty-generated.yaml

Afaik this is the last feature needed to achieve feature parity with Flavours. There is more information in this discussion: https://github.com/Misterio77/flavours/issues/85
Make sure to first `git checkout` out this branch.
- Print to stdout: `cargo run generate-scheme path/to/image.png -`
- Outfile: `cargo run generate-scheme path/to/image.png path/to/outfile.yaml`
- Save scheme: `cargo run generate-scheme path/to/image.png --save` to save it and `cargo run list --custom` to print these schemes
These are the basics, `cargo run generate-scheme --help` for more info about setting slug, author, name, etc.

Add `generate-scheme` subcommand

---

USAGE.md

This gets the job done from anywhere since we may be running from another terminal which wouldn't see the `$TMUX` variable.
Thanks for the work on tinty and thanks for refactoring the tmux bits in order to keep the cosmetics separate from the data. Much appreciated. :+1:

better tmux check

---

USAGE.md

Avoids seeing the output when launching new shells.

redirect stdout but leave stderr in play

---

CHANGELOG.md
src/utils.rs

When `tinty generate-scheme` has been used or custom schemes are added to `~/.local/share/tinted-theming/tinty/custom-schemes` and `tinty apply` is run, apply behaves differently: Instead of just applying the theme, it builds each template first (using `tinted-builder-rust`). This is necessary to be able to have custom schemes exist for templates. 
Currently `tinty update` checks to see if there are any diffs, if there are it does not update and asks the user to remove all of their changes to the repo first. This is where the problem lies since the templates contain themes that aren't in the git history so tinty won't update when custom schemes are used.
The change in this PR changes the diff check to allow untracked files since there is low risk of a conflict with a git pull in that …

Fix bug where Tinty won't update local templates with custom schemes

---

USAGE.md

I have the [tinty_source_shell_theme](https://github.com/tinted-theming/tinty/blob/main/USAGE.md#sourcing-scripts-that-set-environment-variables) function defined in my environment which runs each time I start a shell.
After noticing some oddness with my shell colors, I decided to poke around in the directory used to store the .sh files which are sourced by the function above. That's when I noticed an orphan:
```
> ls -go .local/share/tinted-theming/tinty/*.sh
-rw-rw-r-- 1 5102 Sep 15 18:00 .local/share/tinted-theming/tinty/base16-shell-scripts-file.sh
-rw-rw-r-- 1  428 Sep 24 23:14 .local/share/tinted-theming/tinty/tinted-fzf-sh-file.sh
-rw-rw-r-- 1 5109 Sep 24 23:14 .local/share/tinted-theming/tinty/tinted-shell-scripts-file.sh
```
I'm thinking I mucked something up along the way as …

Do not source orphaned sh files

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/operations/apply.rs
tests/cli_apply_subcommand_tests.rs

Fix bug where tinted-builder-rust displays logging information when `cargo apply` is run

Release 0.20.1 - fix logging bug

---

CHANGELOG.md
README.md
contrib/completion/tinty.bash
contrib/completion/tinty.elvish
contrib/completion/tinty.fish
contrib/completion/tinty.powershell
contrib/completion/tinty.zsh
src/cli.rs
src/main.rs
src/operations/current.rs
tests/cli_current_subcommand_tests.rs
tests/utils.rs

Adds optional argument for `tinty current <arg>` subcommand. Accepted arg value options are `author`, `description`,  `name`, `slug`, `system`, `variant`.  This is backward compatible since `tinty current` will function the same as it did before.

Add feature to get specific scheme information from current scheme

---

README.md

I packaged `tinty` for the AUR, it is available here: https://aur.archlinux.org/packages/tinty-git
I added the install instructions.
closes #76

Add arch linux install instructions

---

tests/utils.rs

Assuming that the executable always lives in `./target/release/tinty` is not sound depending on the Cargo setup. Instead, one should rely on existing environment variables to be more robust (see https://doc.rust-lang.org/cargo/reference/environment-variables.html)

tests/utils: use CARGO_BIN_EXE* to find tinty executable

---

CHANGELOG.md
Cargo.lock
Cargo.toml
LICENSES-THIRD-PARTY.md
deny.toml

- Use latest [tinted-scheme-extractor](https://github.com/tinted-theming/tinted-scheme-extractor-rs) which includes adjustments to >= `base08` colors to ensure they are brighter than a certain threshold
- Update crate deps

Update Cargo dependencies and update to latest tinted-scheme-extractor

---

CHANGELOG.md
src/operations/apply.rs

☝️ As the title says, if the theme file doesn't have a file extension, the generated file will have a trailing dot e.g.:
```sh
~/.local/share/tinted-theming/tinty/repos/tinted-terminal/themes/ghostty/base16-3024
~/.local/share/tinted-theming/tinty/tinted-terminal-themes-ghostty-file.
```
This is probably not a common case, but Ghostty uses the theme filename as the theme name itself. This patch makes it so that these kinds of files are copied over without an extension.
(I'm new to Rust 🙃 so apologies in advance!)

fix: generate file have trailing dot of theme file doesn't have a file extension

---

README.md

Minor typo and formatting fixes for README.md
* Removed superfluous line break
* Corrected title casing for Arch Linux
* Changed "eg" into "e.g." throughout
* Fixed broken link to third-party licenses

docs: Minor fixes in README.md

---

.github/workflows/release-commit.yml
RELEASE.md
scripts/create_release_changes

To create a release, currently a few things should be run before running the "Release" github action (which builds the tinty binaries and publishes the latest version to crates.io). The things that need to be done is:
- Bump `Cargo.toml` version to a minor or patch version. `minor` if there are new additions or breaking changes and `patch` if it's solely a bug fix
- Cargo.lock should be automatically updated once `Cargo.toml` version is bumped
- CHANGELOG.md should rename `## Unreleased` to `## [x.x.x] - yyyy-mm-dd` and a link added at the bottom of the file to link the diff of `[x.x.x]` with the previous version
- Update THIRD-PARTY-LICENSES.md
I usually do this manually but I've made mistakes before and if other people join as maintainers, it's best to automate this process, so that's …

Create a release-commit action

---

CHANGELOG.md
src/constants.rs
src/operations/list.rs
src/utils.rs
tests/cli_list_subcommand_tests.rs

Previously, only scheme files with `*.yaml` extension were recognized. Custom schemes with `*.yml` extensions, for example, were ignored.

fix: Schemes with `*.yml` extension is not recognized

---

CHANGELOG.md
src/utils.rs

Related to https://github.com/tinted-theming/tinty/issues/100
- Remove `--branches` flag. I know the flag limits it to branches, but I don't think it shouldn't ever match anything else.
- Fixes in the file suggested by `cargo clippy`

Fix bug where `--branches` flag doesn't exist for some versions of git

---

scripts/create_release_changes

- Exit with error if version isn't bumped correctly
- Fix bug where version isn't set correctly with function

Fix create_release_changes github action script bugs

---

deny.toml
tests/cli_list_subcommand_tests.rs

There are a lot more Base24 schemes now

chore: update known scheme count in test assertions

---

.gitignore
CHANGELOG.md
README.md
src/cli.rs
src/config.rs
src/main.rs
src/operations/current.rs
src/operations/cycle.rs
src/utils.rs
tests/cli_current_subcommand_tests.rs
tests/cli_cycle_subcommand_tests.rs
tests/utils.rs

@JamyGolden What do you think of a feature like this?
The most common use-case by far I use Tinty for is switching between a couple of dark and light themes, and I think this is probably true for others. I thought it would be convenient if there was a way to quickly apply one's favorite themes by cycling through a small list the user curated (e.g. one light, one dark)
This PR does this by:
1. Checking the config what the preferred themes are.
2. Resolves what the next theme should be.
3. Consider cases where `default-scheme` is set.
4. Available as `tinty cycle`.
Let me know what you think.

feat: implement `tinty cycle`

---

tests/cli_list_subcommand_tests.rs

`cargo test` is failing on main due to:
```
---- test_cli_list_subcommand_as_json_with_setup stdout ----
thread 'test_cli_list_subcommand_as_json_with_setup' panicked at tests/cli_list_subcommand_tests.rs:449:5:
expected JSON to contain 447 entries, found 459
stack backtrace:
0: __rustc::rust_begin_unwind
1: core::panicking::panic_fmt
2: core::ops::function::FnOnce::call_once
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
This is brittle since it will break when `SCHEMES_COUNT` is compared to a value that will be increased at some point.
This change the test to ensure the scheme-results count is `>=` `SCHEMES_COUNT`.

Fix test which directly depends on scheme count

---

.github/workflows/create-release-commit.yml
.github/workflows/create-release-git-tag.yml
.github/workflows/release.yml
RELEASE.md

Consolidate two release steps into 1 for simplicity. The idea is someone can just run the `Release` workflow and everything is great. I've added some debugging steps in RELEASE.md.
PR should be ok, still in draft though since workflows are always a pain to get right so I want to look at it more and get any suggestions/comments from you @bezhermoso

Simplify release workflow

---

USAGE.md

The usage instructions to source hook scripts to allow setting env vars search for `*.sh` files, but those scripts are actually symbolic links, thus the `find` command never fins any and the function does not work.
by replacing `-type f` with `-type l` the function works.
I myself simplify this script by simply redefining the `tinty`  command with a function, so there is no need for the alias:
```bash
tinty() {
newer_file=$(mktemp)
command tinty $@
subcommand="$1"
if [ "$subcommand" = "apply" ] || [ "$subcommand" = "init" ]; then
tinty_data_dir="${XDG_DATA_HOME:-$HOME/.local/share}/tinted-theming/tinty"
while read -r script; do
. "$script"
done < <(find "$tinty_data_dir" -maxdepth 1 -type l -name "*.sh" -newer "$newer_file")
unset tinty_data_dir
fi
unset subcommand
}
```

Update usage instructions to source hooks
